package controller;

public enum Commands {
	C_ES_LANGUAGE, C_EN_LANGUAGE, ADD_AVOCADO,
	SHOW_GRAPHIC, DELETE_CHAIN, GET_ID_DEPARTMENT,
	CALCULATE_PERFORMANCE, ACCEPT_BUTTON_CHAIN,
	ACCEPT_BUTTON_DELETE, CANCEL_BUTTON_CHAIN,
	CANCEL_BUTTON_DELETE, SEARCH_DELETE,
	BLACKBERRY_BUTTON, STRAWBERRY_BUTTON,
	LULO_BUTTON, BANANA_BUTTON,
	PASSION_FRUIT_BUTTON, PEACH_BUTTON

}
