package controller;

public enum Commands {
	C_ES_LANGUAGE, C_EN_LANGUAGE, ADD_FRUIT,
	SHOW_GRAPHIC, DELETE_CHAIN, GET_ID_DEPARTMENT,
	CALCULATE_PERFORMANCE, ACCEPT_BUTTON_CHAIN,
	ACCEPT_BUTTON_DELETE, CANCEL_BUTTON_CHAIN,
	CANCEL_BUTTON_DELETE, SEARCH_DELETE,
	BLACKBERRY_BUTTON, STRAWBERRY_BUTTON,
	LULO_BUTTON, BANANA_BUTTON,
	PASSION_FRUIT_BUTTON, PEACH_BUTTON, 
	BUTTON_CHANGE_HOME, BUTTON_CHANGE_EXPORT,
	BUTTON_CHANGE_GRAPHICS, BUTTON_CHANGE_TABLE,
	GET_FRUIT, BUTTON_FACEBOOK, BUTTON_INSTAGRAM,
	BUTTON_JSON, BUTTON_XML, BUTTON_BINARY,
	BUTTON_TEXT, BUTTON_YOUTUBE, REPORT_ONE,
	REPORT_TWO, REPORT_THREE, REPORT_FOUR, REPORT_FIVE,
	REPORT_SIX, REPORT_SEVEN, REPORT_EIGHT, REPORT_NINE,
	REPORT_TEN, GRAPHIC_ONE, GRAPHIC_TWO,
	GRAPHIC_THREE, GRAPHIC_FOUR, GRAPHIC_FIVE,
	GRAPHIC_NINE, GRAPHIC_SEVEN, GRAPHIC_EIGHT,
	GRAPHIC_TEN, GRAPHIC_SIX

}
